### ISSUE TITLE
Example app do not cover expired sessions and multi user

### ISSUE THREAD

**Issue by bpsushi** [Shopify/shopify-app-node#575]
# Issue summary
This example app do not cover basic scenarios like expired session, or multiple users using the app.
For example - when there is staff member account in shop, and the app is already installed, verifyRequest will always fail, since shop is already stored in ACTIVE_SHOPIFY_SHOPS. Session will never be created, and any call to`/graphq` endpoint will result in redirect to `/auth` - which will obviously not work.

## Expected behavior
This app example should cover both scenarios:
- expired session
- user that do not have session yet

## Actual behavior
Example app do not cover given scenarios, verifyRequest middleware redirect to `/auth` even if it is apollo call to `/graphql`

## Steps to reproduce the problem

1. Setup example app as given in Readme
2. Add some page that is using Apollo Client (for example as given in Shopify tutorial https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/learn-the-graphql-admin-api)
2. Authenticate app in your store
3. Create staff member account in your store
4. Log in as staff member and go to the app
5. Try to use page that is making requests to `/graphql`

## Reduced test case
-

## Specifications

- Browser: Any
- Device: Any
- Operating System: Any

**Comment by paulomarg** [comment]
Hey @bpsushi, thanks for reporting this. You're right, the example app only tracks whether a certain shop has already performed OAuth, which only makes sense for offline tokens.

For online tokens, the app could send a header back on expired sessions that tells the frontend where to go for re-auth. We could add that as a toggle to `verifyRequest`, to send a header with the OAuth URL back instead of the redirection page contents. One could then wrap the `authenticatedFetch` call in the frontend to go to that header if it's present in the response.

We'll update the example app and tutorial to do that instead of the `SHOPIFY_ACTIVE_SHOPS` approach.

**Comment by bpsushi** [comment]
@paulomarg thank you for response! Adding toggle to `verifyRequest` is perfect solution for ajax reachable routes.
