### ISSUE TITLE
Can not show a page which has `getServerSideProps `

### ISSUE THREAD

**Issue by tomoyukikashiro** [Shopify/shopify-app-node#591]
# Issue summary

A page which has `getServerSideProps ` (example below) return 400 error after redirecting `/auth`.

**current page**

```js
import { Heading, Page } from "@shopify/polaris";
import Link from 'next/link'

const Index = () => (
  <Page>
    <Heading>Shopify app with Node and React 🎉</Heading>
    <ul>
      <li><Link href={'/serversideprops'}><a>page with serverSideProps</a></Link></li>
    </ul>
  </Page>
);

export default Index;
```

**destination page**
```js
export async function getServerSideProps(context) {
  return {
    // Usually, we will get user's data from our DB.
    // But I set data for now. because it's demo.
    props: {
      time: (new Date()).toLocaleTimeString()
    }
  }
}

const ServerSideProps = ({time}) => (
  <>
    <h1>page with serverSideProps.</h1>
    <p>{time}</p>
  </>

)

export default ServerSideProps
```

Do you have any solution to fix this issue ???

## Expected behavior

The page with getServerSideProps should be shown correctly.

## Actual behavior

After clicking the page link only **Bad Request** message was shown.

![image](https://user-images.githubusercontent.com/666939/112592568-87fa0b80-8e49-11eb-8011-68fc21ce8ff1.png)

Network looks like below.

![image](https://user-images.githubusercontent.com/666939/112592437-508b5f00-8e49-11eb-9065-97371ceae5ce.png)

## Steps to reproduce the problem

1. clone [this repo](https://github.com/tomoyukikashiro/shopify-node-app-multiple-pages-demo)
2. `$ shopify serve`
3. click `page with serverSideProps` link in index page

## Specifications

- Browser: Chrome 89.0.4389.90
- Device: Mac mini (2018)
- Operating System: MacOS Catalina 10.15.7

**Comment by paulomarg** [comment]
Hey @tomoyukikashiro, based on your network requests it seems that your request for `serversideprops` is reaching the server, and failing on `verifyRequest` in the `(.*)` route, because it doesn't have the `Authorization` header (which is set by `authenticatedFetch`).

There's been a [similar discussion](https://github.com/Shopify/koa-shopify-auth/issues/76#issuecomment-805844570) in the `koa-shopify-auth` repo. I think you'll probably want to use a `ClientRouter` here so the request for the `serversideprops` page doesn't reach the server.

Also, if you're requesting data from the server inside `getServerSideProps`, you'll want to use `authenticatedFetch` from App Bridge, rather than a plain `fetch`.

Hope this helps!

**Comment by paulomarg** [comment]
Hey @tomoyukikashiro, yes, that's right! Embedded apps can't use cookies any more, so only requests made with `authenticatedFetch` after App Bridge is loaded can get the access token.

**Comment by tomoyukikashiro** [comment]
@paulomarg Thank you for your help !
