### ISSUE TITLE
Verify session token of non-root request

### ISSUE THREAD

**Issue by NoharaMasato** [Shopify/shopify-app-node#655]
# Issue summary

Based on this comment,
https://github.com/Shopify/shopify-app-node/pull/633#issuecomment-889629063
I guess session token of non-root request will not be verified.

## Expected behavior
Session token of non-root request should be verified using `verifyRequest `

**Comment by paulomarg** [comment]
Hi @NoharaMasato, you're correct, those requests will by default not be verified.

The reason for that is that in our example app, the fallback route will handle all of the full page loads, which is what the `/` endpoint does now - it just loads a splash/skeleton page that builds App Bridge and makes requests that will work with `verifyRequest`.

In the example app, the flow of requests is:
1. `/` - loads skeleton page that builds App Bridge
2. `/graphql` - request fired using App Bridge that can be verified by `verifyRequest`

Essentially, when using session tokens, `verifyRequest` won't work unless the request was made using `authenticatedFetch` from App Bridge, so we can't call it on a server-side rendered request like `/`. Our example is an embedded single-page app that only loads `/` from the server, and renders the other pages client-side.

It's also worth mentioning that while the `/` endpoint (and any other that reaches the fallback) will be unauthenticated, any request that actually fetches data should go to the `/graphql` endpoint, which will verify the request and trigger the OAuth process if necessary.

I hope this helps clarify the issue. Since this is not an actual problem in the app, I'm going to go ahead and close this issue, but please feel free to open a new issue if you find something that is not working as expected.
